{
 "title": "AWS MSK - Kafka Cluster-CloudWatch",
 "description": "Dashboard for Basic AWS MSK Cluster metrics visualisation",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "dimension_values($region,AWS/Kafka,CpuIdle,Cluster Name)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ActiveControllerCount",
   "type": "stat",
   "description": "Only one controller per cluster should be active at any given time.\n",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Brokers with PartitionCount",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "PartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Brokers with SessionState",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "PartitionCount",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "PartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "ZooKeeperSessionState",
   "type": "stat",
   "description": "Connection status of broker's ZooKeeper session which may be one of the following: \n\nNOT_CONNECTED: '0.0', \n\nASSOCIATING: '0.1', \n\nCONNECTING: '0.5', \n\nCONNECTEDREADONLY: '0.8', \n\nCONNECTED: '1.0', \n\nCLOSED: '5.0', \n\nAUTH_FAILED: '10.0'.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperSessionState",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "LeaderCount",
   "type": "stat",
   "description": "The total number of leaders of partitions per broker, not including replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "LeaderCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "SumOffsetLag",
   "type": "timeseries",
   "description": "The aggregated offset lag for all the partitions in a topic.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster", "Consumer Group": "*" },
     "metricName": "SumOffsetLag",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ZooKeeperRequestLatency MsMean",
   "type": "timeseries",
   "description": "The mean latency in milliseconds for Apache ZooKeeper requests from broker.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "ZooKeeperRequestLatencyMsMean",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "GlobalPartition/GlobalTopic Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$cluster" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CpuIdle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "CpuIdle",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CpuSystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "CpuSystem",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CpuUser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "CpuUser",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "MemoryFree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "MemoryFree",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MemoryUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "MemoryUsed",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MemoryCached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "MemoryCached",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "MemoryBuffered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "MemoryBuffered",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "KafkaDataLogsDiskUsed ",
   "type": "timeseries",
   "description": "The percentage of disk space used for data logs.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "KafkaDataLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "KafkaAppLogsDiskUsed",
   "type": "timeseries",
   "description": "The percentage of disk space used for application logs.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "KafkaAppLogsDiskUsed",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "RootDiskUsed",
   "type": "timeseries",
   "description": "The percentage of the root disk used by the broker.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "RootDiskUsed",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "NetworkTxPackets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkTxPackets",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkTxErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkTxErrors",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkTxDropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkTxDropped",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkRxPackets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkRxPackets",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkRxErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkRxErrors",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "NetworkRxDropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "p/m" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "$cluster" },
     "metricName": "NetworkRxDropped",
     "namespace": "AWS/Kafka",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}